# Generated by Django 5.1.3 on 2024-11-13 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('detailed_description', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='projectApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('event_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projectApp.eventdetail')),
            ],
        ),
    ]
